name: Build and push

on: push

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: stianovrevage/grafana-dashboard-cloner
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}